#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE DATABASE datastore
    OWNER ${POSTGRES_USER};

DO \$\$
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles WHERE rolname = '${CKAN_DATASTORE_READ_USER}'
    ) THEN
        CREATE ROLE ${CKAN_DATASTORE_READ_USER} NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN
            PASSWORD '${CKAN_DATASTORE_READ_PASSWORD}';
    END IF;
END
\$\$;
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname datastore <<SQL
GRANT CONNECT ON DATABASE datastore TO ${CKAN_DATASTORE_READ_USER};
GRANT USAGE ON SCHEMA public TO ${CKAN_DATASTORE_READ_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${CKAN_DATASTORE_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${CKAN_DATASTORE_READ_USER};
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";
CREATE EXTENSION IF NOT EXISTS "unaccent";
SQL
